--Reset
DROP DATABASE IF EXISTS RAW;
DROP DATABASE IF EXISTS CORE;

--Setup
CREATE DATABASE IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS RAW.S3;
CREATE DATABASE IF NOT EXISTS CORE;
CREATE SCHEMA IF NOT EXISTS CORE.PLATFORM;

